workflows:
  build-android:
    name: Build Android
    instance_type: linux
    environment:
      groups:
        - google-play-credentials
      android_signing:
        - capybara-keystore
    scripts:
      - flutter packages pub get
      - flutter build appbundle --release --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - 'build/app/outputs/**/*.aab'
      - 'build/app/outputs/**/*.apk'
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: alpha
        release_promotion:
          track: internal
          rollout_fraction: 0.5
