workflows:
  wf:
    instance_type: windows_x2
    environment:
      xcode: 13.3
      vars:
        v: value
      groups:
        - g1
        - g2
        - s
        - team
        - App Store Connect API
#       ios_signing:
#         distribution_type: development
#         bundle_identifier: io.codemagic.capybara
      android_signing:
        - codemagic-key
    scripts:
      - printenv
      - python -c "import subprocess; subprocess.run('app-store-connect get-profile kana', shell=True)"
#       - app-store-connect get-profile kana || true
    artifacts:
      - /tmp/xcodebuild_logs/*.log
  empty:
    name: Empty
    environment:
      xcode: 13.3
    scripts:
      - echo "empty"
